// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNT_PROYECTO.Data;

#nullable disable

namespace PNT_PROYECTO.Migrations
{
    [DbContext(typeof(PNT_PROYECTOContext))]
    [Migration("20221025003949_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("PNT_PROYECTO.Models.Examen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlumnoLegajo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoLegajo");

                    b.ToTable("Examen");
                });

            modelBuilder.Entity("PNT_PROYECTO.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("PNT_PROYECTO.Models.Persona", b =>
                {
                    b.Property<int>("Legajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Legajo");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("PNT_PROYECTO.Models.Alumno", b =>
                {
                    b.HasBaseType("PNT_PROYECTO.Models.Persona");

                    b.HasDiscriminator().HasValue("Alumno");
                });

            modelBuilder.Entity("PNT_PROYECTO.Models.Profesor", b =>
                {
                    b.HasBaseType("PNT_PROYECTO.Models.Persona");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("PNT_PROYECTO.Models.Examen", b =>
                {
                    b.HasOne("PNT_PROYECTO.Models.Alumno", null)
                        .WithMany("ExamenesList")
                        .HasForeignKey("AlumnoLegajo");
                });

            modelBuilder.Entity("PNT_PROYECTO.Models.Alumno", b =>
                {
                    b.Navigation("ExamenesList");
                });
#pragma warning restore 612, 618
        }
    }
}
